### ISSUE TITLE
input.txt should not be available

### ISSUE THREAD

**Issue by TomConlin** [helenzhangyc/aoc2024#1]
just a heads up

per: https://adventofcode.com/2024/about

'''

Can I copy/redistribute part of Advent of Code? Please don't. Advent of Code is free to use, not free to copy. If you're posting a code repository somewhere, please don't include parts of Advent of Code like the puzzle text or your inputs. If you're making a website, please don't make it look like Advent of Code or name it something similar

'''
I ran afoul thinking input files were all the same 
and grabbed yours as I had not noticed where mine was.  
they noticed and mentioned it.

you should likely add their inout files to your .gitignore

**Comment by helenzhangyc** [comment]
I see I see, thanks for pointing out! Just added them to `.gitignore`
